/**
 * ARQUIVO DE CONFIGURAÇÃO DE CONTEÚDO - TCC SBV
 * Use este arquivo para editar manualmente o texto do TCLE, perguntas e flashcards.
 */// 1. QUESTÕES DO SIMULADOR (Treino prático)
const quizQuestions = [
    { cat: "Segurança", q: "Qual a prioridade absoluta ao abordar uma vítima caída?", opts: ["Verificar pulso.", "Segurança da cena.", "Iniciar RCP imediatamente.", "Gritar por socorro."], correct: 1, explanation: "Segurança em primeiro lugar: não se torne uma nova vítima." },
    { cat: "Avaliação", q: "Como testar a responsividade de um adulto?", opts: ["Dar um tapa no rosto.", "Chamar alto e tocar nos ombros.", "Sacudir o tronco vigorosamente.", "Gritar próximo ao ouvido."], correct: 1, explanation: "Toque firme nos ombros e voz alta." },
    { cat: "Leigos", q: "Qual é a recomendação para leigos não treinados em RCP?", opts: ["Realizar ventilações.", "Apenas compressões (Hands-Only).", "Seguir o ciclo 30:2.", "Aguardar o socorro sem intervir."], correct: 1, explanation: "Hands-Only simplifica o processo e mantém a oxigenação cerebral." },
    { cat: "Técnica", q: "Qual é a frequência ideal das compressões torácicas?", opts: ["80 BPM.", "100-120 BPM.", "O mais rápido possível.", "Exatamente 60 BPM."], correct: 1, explanation: "Frequência ideal para garantir o débito cardíaco." },
    { cat: "Técnica", q: "Qual a profundidade ideal das compressões no adulto?", opts: ["Cerca de 2 cm.", "Cerca de 4 cm.", "Entre 5 e 6 cm.", "No mínimo 8 cm."], correct: 2, explanation: "Menos é ineficaz, mais pode causar traumas graves." },
    { cat: "Mecânica", q: "Por que permitir o recuo total do tórax entre as compressões?", opts: ["Para o socorrista descansar.", "Para permitir o reenchimento cardíaco.", "Para evitar dor na vítima.", "Como sinal de fim do ciclo."], correct: 1, explanation: "O sangue precisa retornar ao coração para ser bombeado na próxima compressão." },
    { cat: "Protocolo", q: "Qual a relação C:V recomendada para adultos (SBV)?", opts: ["15:2.", "30:2.", "50:2.", "Apenas compressões contínuas."], correct: 1, explanation: "Padrão recomendado para via aérea básica." },
    { cat: "Equipamento", q: "O DEA chegou. Qual é a primeira ação a ser tomada?", opts: ["Colar as pás.", "Ligar o aparelho.", "Pedir para todos se afastarem.", "Trocar de socorrista."], correct: 1, explanation: "Ligar o aparelho inicia o protocolo guiado por voz." },
    { cat: "OVACE", q: "Vítima tosse ruidosamente e fala. Qual a conduta?", opts: ["Realizar manobra de Heimlich.", "Dar tapas nas costas.", "Apenas encorajar a tosse.", "Iniciar RCP."], correct: 2, explanation: "A tosse parcial é o mecanismo de defesa mais eficaz." },
    { cat: "Fisiologia", q: "Como deve ser interpretado o 'Gasping'?", opts: ["Sinal de melhora.", "Respiração normal.", "Sinal de PCR (Parada Cardiorrespiratória).", "A vítima está acordando."], correct: 2, explanation: "Não é uma respiração funcional. Inicie RCP imediatamente." },
    { cat: "OVACE", q: "Qual o protocolo para desengasgo consciente grave?", opts: ["Apenas manobra de Heimlich.", "Alternância: 5 tapas + 5 compressões.", "Oferecer água.", "Bater no peito."], correct: 1, explanation: "A alternância de pressões aumenta a eficácia da desobstrução." },
    { cat: "Gestantes", q: "Qual o local correto para compressões em gestantes engasgadas?", opts: ["Abdômen superior.", "Centro do tórax (esterno).", "Nas costas.", "Apenas tapas dorsais."], correct: 1, explanation: "A anatomia da gestação avançada exige compressões torácicas." },
    { cat: "Lactentes", q: "Qual a conduta para desengasgo em bebês (< 2 anos)?", opts: ["Manobra de Heimlich.", "Elevar as pernas.", "5 tapas dorsais + 5 compressões torácicas.", "Sacudir o bebê."], correct: 2, explanation: "Compressões abdominais podem lesionar órgãos internos de lactentes." },
    { cat: "Fisiologia", q: "O cérebro sofre dano tecidual por hipóxia após quantos minutos?", opts: ["1 minuto.", "4 a 6 minutos.", "30 minutos.", "1 hora."], correct: 1, explanation: "Janela crítica para evitar sequelas neurológicas." },
    { cat: "Fadiga", q: "Por que trocar o socorrista (compressor) a cada 2 minutos?", opts: ["Cansaço mental.", "A fadiga física reduz a qualidade das compressões.", "Apenas por regra de protocolo.", "Para checar o pulso."], correct: 1, explanation: "A fadiga reduz a eficácia mesmo que o socorrista não se sinta cansado." }
];

// 2. QUESTÕES DA AVALIAÇÃO (Pré e Pós-teste)
const finalExamQuestions = [
    { q: "As condutas relacionadas a etapa de “Vigilância e Prevenção” que compõe a Cadeia da Sobrevivência, para atendimento da Parada Cardiorrespiratória (PCR) no ambiente hospitalar são:", opts: ["Identificação da Parada Cardiorrespiratória; Definição de intervenções efetivas; Detalhamento da queixa.", "Identificação da Parada Cardiorrespiratória; Implementação de avaliação clínica detalhada; Definição de intervenções efetivas.", "Implementação de avaliação clínica com detalhamento da queixa e Definição de intervenções efetivas.", "Implementação de avaliação clínica detalhada e da Ressuscitação Cardiopulmonar; Definição de intervenções efetiva."], correct: 2 },
    { q: "Na etapa de “Reconhecimento precoce e pedido de ajuda” deve ser solicitada ajuda imediatamente após identificada a irresponsividade da vítima. Esta etapa consiste em providenciar:", opts: ["Suporte Médico, Carrinho de emergência com desfibrilador e sistema de ventilação.", "Suporte Médico e sistema de ventilação.", "Carrinho de emergência com desfibrilador e sistema de ventilação.", "Suporte Médico, Carrinho de emergência com desfibrilador."], correct: 0 },
    { q: "A sequência de ações que leva o profissional a reconhecer irresponsividade em uma vítima suspeita de Parada Cardiorrespiratória (PCR) é:", opts: ["Toque superficial ao nível dos ombros da vítima com estímulo auditivo intenso, se possível, chamando a vítima pelo nome.", "Toque superficial ao nível dos ombros e estímulo auditivo, se possível, chamando a vítima pelo nome.", "Toque intenso ao nível dos ombros da vítima com estímulo auditivo, obrigatoriamente, chamando a vítima pelo nome.", "Toque intenso ao nível dos ombros da vítima com estímulo auditivo também intenso, se possível, chamando a vítima pelo nome."], correct: 3 },
    { q: "Na avaliação do pulso e respiração no reconhecimento da Parada Cardiorrespiratória (PCR) o profissional deve:", opts: ["Verificar pulso carotídeo e, na sequência, respiração, em menos de dez segundos.", "Verificar pulso carotídeo e, simultaneamente, respiração em menos de dez segundos.", "Verificar pulso carotídeo e respiração simultaneamente em menos de cinco segundos.", "Verificar pulso carotídeo e, na sequência, respiração, em menos de cinco segundos."], correct: 1 },
    { q: "Considerando as ações imediatas mediante o reconhecimento da Parada Cardiorrespiratória (PCR), analise o cenário: “X e Y são enfermeiros e estão na Sala de Emergência de um hospital, onde é admitido um paciente em Parada Cardiorrespiratória (PCR)”. A conduta recomendada a ser realizada de maneira simultânea por X e Y é:", opts: ["Y inicia as Compressões Torácica Externa e X implementa a etapa de “Pedido de ajuda”.", "Y inicia as Compressões Torácica Externa e X permeabiliza as Vias Aéreas.", "Y implementa a etapa de “Pedido de Ajuda” e X permeabiliza as Vias Aéreas.", "Y implementa a etapa de “Pedido de Ajuda” e X realiza ventilação com Bolsa-valva-máscara."], correct: 0 },
    { q: "A troca de profissional durante a realização da Compressão Torácica Externa (CTE) é ser a cada:", opts: ["90 segundos.", "120 segundos.", "180 segundos.", "60 segundos."], correct: 1 },
    { q: "O local indicado, no tórax da vítima, para posicionamento das mãos do profissional na execução da Compressão Torácica Externa (CTE) é:", opts: ["Terço médio do esterno.", "Metade superior do esterno.", "Terço inferior do esterno.", "Metade inferior do esterno."], correct: 3 },
    { q: "A profundidade indicada nas Compressões Torácica Externa (CTE) de uma vítima adulta é:", opts: ["Pelo menos 4cm, mas não deve ser superior a 5cm.", "Pelo menos 6cm, mas não deve ser superior a 8cm.", "Pelo menos 5cm, mas não deve ser superior a 6cm.", "Pelo menos 4cm, mas não deve ser superior a 6cm."], correct: 2 },
    { q: "A frequência, por minuto, indicada nas Compressões Torácica Externa (CTE) é:", opts: ["100 a 120 por minuto.", "60 a 90 por minuto.", "Superior a 120 e inferior a 140.", "Superior a 60 e inferior a 100."], correct: 0 },
    { q: "Em relação ao retorno da parede torácica pela descompressão na Compressão Torácica Externa (CTE), o profissional deve:", opts: ["Garantir leve afastamento do tórax pelas mãos do profissional.", "Permitir o retorno total do tórax.", "Manter leve compressão no tórax.", "Realizar o movimento de “galope” (afastar região hipotênar do tórax da vítima) pelas mãos do profissional."], correct: 1 },
    { q: "Para a permeabilização das Vias Aéreas (VVAA), na Ressuscitação Cardiopulmonar (RCP), quando não há suspeita de lesão cervical, é indicado:", opts: ["Elevação da cabeça pela flexão do pescoço.", "Lateralização da cabeça pela hiperextensão do pescoço.", "Elevação da cabeça pela hiperextensão do pescoço.", "Lateralização da cabeça pela flexão do pescoço."], correct: 2 },
    { q: "Para realizar o manejo adequado da bolsa durante a ventilação com Bolsa-valva-máscara deve:", opts: ["Pressionar lentamente todo o centro da bolsa, em cada ventilação.", "Pressionar rapidamente, em seis segundos, as extremidades da bolsa, em cada ventilação.", "Pressionar lentamente as extremidades da bolsa, em cada ventilação.", "Pressionar rapidamente, em um segundo, todo o centro da bolsa, em cada ventilação."], correct: 3 },
    { q: "Em uma vítima adulta, quando a Compressão Torácica Externa (CTE) é realizada sincronizadas com a ventilação por Bolsa-valva-máscara é recomendado:", opts: ["Realizar ciclos de 30 Compressões Torácica Externa acompanhadas por duas Ventilações de resgate com Bolsa-valva-máscara.", "Realizar ciclos de 15 Compressões Torácica Externa acompanhadas por uma Ventilação de resgate com Bolsa-valva-máscara.", "Realizar ciclos de 20 Compressões Torácica Externa acompanhadas por duas Ventilações de resgate por Bolsa-valva-máscara.", "Realizar ciclos de 50 Compressões Torácica Externa acompanhadas por uma Ventilação de resgate por Bolsa-valva-máscara."], correct: 0 },
    { q: "Na chegada do Desfibrilador Externo Automático (DEA) no local da Parada Cardiorrespiratória (PCR), a conduta imediata é:", opts: ["Aderir as pás no tórax da vítima.", "Finalizar o ciclo das Compressões Torácica Externa.", "Abrir e ligar o equipamento.", "Interromper as Compressões Torácica Externa para implementar o Desfibrilador Externo Automático (DEA)."], correct: 2 },
    { q: "Na vítima em Parada Cardiorrespiratória (PCR), os ritmos cardíacos que não são indicados o choque pelo Desfibrilador Externo Automático (DEA) são:", opts: ["Atividade Elétrica sem Pulso e Taquicardia Ventricular sem pulso.", "Fibrilação Ventricular e Assistolia.", "Fibrilação Ventricular e Taquicardia Ventricular sem pulso.", "Assistolia e Atividade Elétrica sem Pulso."], correct: 3 },
    { q: "Considerando os ritmos cardíacos em que acontece a indicação do choque pelo Desfibrilador Externo Automático (DEA), avalie o cenário: “X e Y estão em atendimento de uma Parada Cardiorrespiratória (PCR) com o uso do Desfibrilação Externa Automática (DEA), o equipamento avalia o ritmo e o choque é recomendado”. Os possíveis ritmos cardíacos da vítima são:", opts: ["Assistolia e Atividade Elétrica sem Pulso.", "Fibrilação Ventricular e Taquicardia Ventricular sem pulso.", "Atividade Elétrica sem Pulso e Taquicardia Ventricular sem pulso.", "Fibrilação Ventricular e Assistolia."], correct: 1 },
    { q: "A conduta recomendada ao profissional em um cenário que o Desfibrilador Externo Automático (DEA) avalia o ritmo cardíaco e não indica o choque é:", opts: ["Reiniciar a Ressuscitação Cardiopulmonar.", "Interromper a Ressuscitação Cardiopulmonar.", "Avaliação do pulso e respiração da vítima.", "Reavaliar o ritmo cardíaco."], correct: 2 },
    { q: "Com o retorno da circulação espontânea após uso do Desfibrilador Externo Automático (DEA), é recomendado:", opts: ["Desligar o equipamento e retirar as pás do tórax da vítima.", "Não desligar o equipamento e retirar as pás do tórax da vítima.", "Desligar o equipamento e manter as pás aderidas ao tórax da vítima.", "Não desligar o equipamento e manter as pás aderidas ao tórax da vítima."], correct: 3 },
    { q: "Compõe a quinta e última etapa na Cadeia da Sobrevivência (“Suporte Avançado de Vida - SAV e cuidados pós Parada Cardiorrespiratória - PCR”), para atendimento da Parada Cardiorrespiratória (PCR) no ambiente intra-hospitalar:", opts: ["Investigação para identificação e tratamento da causa da Parada Cardiorrespiratória.", "Aplicação da desfibrilação.", "Assistência exclusiva pelo profissional médico.", "Assistência exclusiva pelo profissional enfermeiro."], correct: 0 },
    { q: "Em relação da divisão dos itens para registro das informações no instrumento In-hospital Utstein Style é correto afirmar:", opts: ["Dividido em três blocos de informações, relacionado ao paciente, ao momento da Parada Cardiorrespiratória e resultados da Ressuscitação Cardiopulmonar.", "Dividido em dois blocos de informações, relacionado ao paciente e ao momento/resultados da Ressuscitação Cardiopulmonar.", "Um único bloco de itens para registro dos resultados da Ressuscitação Cardiopulmonar.", "Dividido em dois blocos de informações, relacionado ao momento da Parada Cardiorrespiratória e resultados da Ressuscitação Cardiopulmonar."], correct: 1 }
];

// 3. FLASHCARDS
const flashcards = [
    { front: "Ritmo RCP Adulto", back: "100-120 BPM", sub: "Ritmo de 'Stayin Alive'", cat: "Técnica" },
    { front: "C : V Adulto", back: "30 : 2", sub: "30 Compressões : 2 Sopros", cat: "Protocolo" },
    { front: "Profundidade Adulto", back: "5 - 6 cm", sub: "Recuo total necessário", cat: "Técnica" },
    { front: "Manobra Bebê", back: "5 Tapas + 5 Comp.", sub: "Cabeça mais baixa que o tronco", cat: "OVACE" },
    { front: "Morte Biológica", back: "10 Minutos", sub: "Estado de irreversibilidade", cat: "Fisiologia" },
    { front: "Testar Resposta", back: "Chamar / Bater", sub: "Ombros por 10s", cat: "Avaliação" },
    { front: "Sigla DEA", back: "Desfibrilador Externo Automático", sub: "Equipamento eletrônico portátil", cat: "Equipamento" },
    { front: "Troca de Socorrista", back: "A cada 2 Minutos", sub: "Evita exaustão e queda de qualidade", cat: "Técnica" },
    { front: "Local Compressão", back: "Centro do Peito", sub: "Metade inferior do osso esterno", cat: "Técnica" },
    { front: "Profundidade Criança", back: "Cerca de 5 cm", sub: "Ou 1/3 do diâmetro do tórax", cat: "Técnica" },
    { front: "Profundidade Lactente", back: "Cerca de 4 cm", sub: "Ou 1/3 do diâmetro do tórax", cat: "Técnica" },
    { front: "Sinal de Asfixia", back: "Mãos no Pescoço", sub: "Sinal universal de engasgo total", cat: "OVACE" },
    { front: "C : V Criança (2 Soc.)", back: "15 : 2", sub: "15 Compressões : 2 Sopros", cat: "Protocolo" },
    { front: "Número do SAMU", back: "192", sub: "Serviço de Urgência no Brasil", cat: "Acionamento" },
    { front: "Recuo do Tórax", back: "Permitir Enchimento", sub: "O sangue precisa retornar ao coração", cat: "Mecânica" }
];
